import type { Metadata } from 'next'
import IranSansWeb from 'next/font/local'
import './globals.css'
import { StoreProvider } from './StoreProvider'
import Navbar from '@/components/navbar'
import { cn } from '@/lib/utils'

const iransansweb = IranSansWeb({ src: './font/iransansweb.ttf' })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <StoreProvider>
            <html lang='en' dir='rtl'>
                <body className={cn('flex flex-col items-center', iransansweb.className)}>
                    <div className='w-full max-w-[700px] px-8 text-purple-700'>
                        <Navbar />
                        {children}
                    </div>
                </body>
            </html>
        </StoreProvider>
    )
}
